# Generated by Django 4.2.4 on 2023-10-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id_Caracteristicas', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristicas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fechasuscripcion', models.DateField()),
                ('SusActiva', models.BooleanField()),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.plan')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('idtipoplan', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_plan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id_tipotarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('numero_telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioxSuscripcion',
            fields=[
                ('id_Usuarioxsuscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=255)),
                ('id_suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.suscripcion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTitular', models.CharField(max_length=255)),
                ('apellidoTitular', models.CharField(max_length=255)),
                ('numero_tarjeta', models.BigIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('codigo_seguridad', models.IntegerField()),
                ('NumAutorizacionTarjeta', models.IntegerField()),
                ('TipoTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.tipotarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='id_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.tarjeta'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.usuario'),
        ),
        migrations.CreateModel(
            name='Planxcaracteristicas',
            fields=[
                ('id_Planxcaracteristicas', models.AutoField(primary_key=True, serialize=False)),
                ('Activa', models.BooleanField()),
                ('detalle', models.CharField(max_length=100)),
                ('id_Caracteristicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.caracteristicas')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='idtipoplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Streaming.tipoplan'),
        ),
    ]
