# Generated by Django 4.2.4 on 2023-12-03 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_tarjeta',
            new_name='tarjeta',
        ),
    ]
