# Generated by Django 4.2.4 on 2023-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Pantallas',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
