# Generated by Django 4.2.4 on 2023-11-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoplan',
            old_name='idtipoplan',
            new_name='id_tipo_plan',
        ),
        migrations.RemoveField(
            model_name='tipoplan',
            name='tipo_plan',
        ),
    ]
