# Generated by Django 4.2.4 on 2023-12-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0002_rename_numero_tarjeta_usuario_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Streaming.usuario'),
            preserve_default=False,
        ),
    ]
