# Generated by Django 4.2.4 on 2023-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0002_alter_client_pantallas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.FloatField(blank=True, max_length=50, null=True)),
                ('HD', models.BooleanField(default=True, null=True)),
                ('UHD', models.BooleanField(default=False, null=True)),
                ('Programas', models.BooleanField(default=True, null=True)),
                ('Cancelar', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Cancelar',
        ),
        migrations.RemoveField(
            model_name='client',
            name='HD',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Pantallas',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Peliculas',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Precio',
        ),
        migrations.RemoveField(
            model_name='client',
            name='UHD',
        ),
        migrations.AddField(
            model_name='client',
            name='Contraseña',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
